### ISSUE TITLE
Invoke-Build RunIntegrationTests closes current session

### ISSUE THREAD

**Issue by Splaxi** [tommagumma/PSServiceBus#8]
When running the `Invoke-Build RunIntegrationTests` in an interactive session, aka running it by hand, while working on new tests, it will close the session after removing / tearing down the test resource group.

I'm in favor for a `Invoke-Build RunIntegrationTestsInteractive`, that doesn't close the session.

But I can't seem to locate where things go wrong. Got any ideas?

**Comment by Splaxi** [comment]
A hack for now is to put in a `Read-Host "Waiting"` at the last line of the `Start-Tests.ps1` file.

**Comment by tmeadon** [comment]
This only happens when tests fail right?  I think it is probably caused by the [assert](https://github.com/tommagumma/PSServiceBus/blob/cf716ab3c164a69f2f3a99da72b0bcfe68bcca2a/PSServiceBus.build.ps1#L66) statement in the RunIntegrationTests task which is supposed to fail the build if any tests fail.  I'm fairly sure [this](https://github.com/nightroman/Invoke-Build/blob/97ef5ea8db6574599580a2f3f6b8bc6664633532/Invoke-Build.ps1#L178) is the implementation for assert - it doesn't stand out to me that it will end the session if the assertion fails however...

Anyway I think there are two ways forward:

1. To run the tests 'interactively' just run `tests\integration\Start-Tests.ps1`
2. We change the method for testing for failed tests to an `if` and `throw` combo like we have in the `LintPowerShellFunctions` task

Since number 1 is not really a solution and that I agree that it's a pain for the session to end if tests fail, I will look into number 2!

**Comment by Splaxi** [comment]
It seems that it is in fact the `Invoke-Build` command that might be the issue.

After my `Read-Host`, you can see that something is written right after i press enter:

![Invoke-Build](https://user-images.githubusercontent.com/8750181/73917796-6eea7000-48c0-11ea-9a91-a7433cb56899.gif) 

I modified the gif to "pause" after I pressed enter, so you could actually read it. The human eye can't read it, because the session closes instantly after I press enter.

Extracting that into a picture you can actually read
![2020-02-06_09h12_50](https://user-images.githubusercontent.com/8750181/73917993-e6200400-48c0-11ea-89be-3cb9746476d4.png)

**Comment by tmeadon** [comment]
There goes my theory!

**Comment by Splaxi** [comment]
I love stuff like this! Let me know if you need anything from me!

**Comment by tmeadon** [comment]
Same...  I will be able to take a proper look later on, for now I suggest you run the 'Start-Tests' script manually.  You could also temporarily modify the script to prevent the resources from being destroyed and then call `Invoke-Pester` manually to save time!

**Comment by Splaxi** [comment]
I'm just starting new sessions all the time, and keeping my `Read-Host` hack for now.

**Comment by Splaxi** [comment]
Running the `Start-Tests` is also terminating my session. So I believe that your

```

$testResults = Invoke-Pester -Strict -PassThru -EnableExit -Script @{
    Path = $PSScriptRoot
    Parameters = @{
        ServiceBusUtils = $sbUtils
    }
}
```

Might be the reason for things running the way they do.

**Comment by Splaxi** [comment]
Removing the `-EnableExit` seems to do the trick.

Now you know, when you will be looking at it...

**Comment by tmeadon** [comment]
Thanks!

**Comment by Splaxi** [comment]
I would just create a new file, for running it interactively. Then we don't break your build pipelines.

**Comment by tmeadon** [comment]
I'll test the build pipeline without that parameter, it should still work...  however I must have put it in there for a reason...

**Comment by Splaxi** [comment]
That is why I wouldn't waste more time on it, but simply create a new file, name it and we can explain users to use that going forward. But maybe something changed in your pipeline or some of the dependencies and it is actually not needed any more 🤷‍♂️🤞

**Comment by tmeadon** [comment]
I removed `-EnableExit` and the build is still working as it should.
